public class SortStudents {

    public static void main(String[] args) {
        System.out.println("Roger Adams\n" +
                "William Alexander\n" +
                "Charles Alvarez\n" +
                "Ann Anderson\n" +
                "Fred Andrews\n" +
                "Alice Baker\n" +
                "Ernest Banks\n" +
                "Billy Bowman\n" +
                "Susan Boyd\n" +
                "Daniel Carter\n" +
                "Sean Castillo\n" +
                "Marilyn Clark\n" +
                "Beverly Clark\n" +
                "Steven Cole\n" +
                "Albert Cruz\n" +
                "Julie Cunningham\n" +
                "Michelle Daniels\n" +
                "Gerald Diaz\n" +
                "Catherine Diaz\n" +
                "Susan Dixon\n" +
                "Richard Edwards\n" +
                "Craig Ellis\n" +
                "Lawrence Evans\n" +
                "Juan Ferguson\n" +
                "Daniel Ferguson\n" +
                "Frances Fisher\n" +
                "Diana Flores\n" +
                "Craig Flores\n" +
                "Gary Foster\n" +
                "Terry Frazier\n" +
                "Anne Freeman\n" +
                "William Garcia\n" +
                "Jonathan Gibson\n" +
                "Jeffrey Gibson\n" +
                "Aaron Gibson\n" +
                "Antonio Gonzalez\n" +
                "Carolyn Grant\n" +
                "Cheryl Gray\n" +
                "Shirley Hall\n" +
                "Mildred Hansen\n" +
                "Andrea Harper\n" +
                "Mildred Hart\n" +
                "Lillian Hart\n" +
                "Victor Harvey\n" +
                "Gloria Harvey\n" +
                "Rose Hernandez\n" +
                "Lawrence Hernandez\n" +
                "Helen Hernandez\n" +
                "Amanda Hernandez\n" +
                "Jesse Howard\n" +
                "Emily Howard\n" +
                "Elizabeth James\n" +
                "Arthur James\n" +
                "David Johnston\n" +
                "Andrea Kelly\n" +
                "Craig King\n" +
                "Heather Knight\n" +
                "Eugene Lawson\n" +
                "Kathryn Lee\n" +
                "Joan Lee\n" +
                "Ashley Lee\n" +
                "Ruby Lewis\n" +
                "Robin Long\n" +
                "Jane Lopez\n" +
                "Sara Mills\n" +
                "James Nelson\n" +
                "Edward Nelson\n" +
                "Tina Olson\n" +
                "Cynthia Olson\n" +
                "Nancy Patterson\n" +
                "Lois Patterson\n" +
                "Frances Peters\n" +
                "Margaret Peterson\n" +
                "Terry Pierce\n" +
                "Catherine Porter\n" +
                "Anne Powell\n" +
                "Marilyn Price\n" +
                "Maria Price\n" +
                "Nicholas Reyes\n" +
                "Justin Reyes\n" +
                "Julie Riley\n" +
                "Stephen Roberts\n" +
                "Melissa Robinson\n" +
                "Antonio Rodriguez\n" +
                "Billy Romero\n" +
                "Edward Rose\n" +
                "Gloria Schmidt\n" +
                "Bonnie Shaw\n" +
                "Fred Simmons\n" +
                "Theresa Simpson\n" +
                "Marie Simpson\n" +
                "Raymond Stewart\n" +
                "Jacqueline Stewart\n" +
                "Rebecca Torres\n" +
                "Kelly Vasquez\n" +
                "Justin Watkins\n" +
                "Gerald Watson\n" +
                "Lawrence Welch\n" +
                "Helen Williamson\n" +
                "Kelly Woods\n");
    }
}
